spring.application.name=NeuroFleetX
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/fleetdb?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=navaroj@1923132
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.jwt.secret=ZmFrZS1uZXVyb2ZsZWV0eC1qd3Qtc2VjcmV0LWtleS1zaG91bGQtYmUtY2hhbmdlZA==
app.jwt.expiration-ms=86400000

server.error.include-message=always
